# Generated by Django 5.0.3 on 2024-03-22 00:09

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
