# Generated by Django 5.0.3 on 2024-03-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_content_alter_category_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(default='images/default.png', upload_to=''),
        ),
    ]
