# Generated by Django 5.0.3 on 2024-03-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='featured_image',
            field=models.ImageField(default='images/default.png', upload_to=''),
        ),
    ]
