# Generated by Django 5.0.3 on 2024-03-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_featured_category_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
    ]
